# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: League of News
email: LeagueOfNews@gmx.fr
description: > # this means to ignore newlines until "baseurl:"
  Votre source française d'informations sur League of Legends.
  Actualité esport, analyses des gros matchs, reflexion sur la meta, revu de patchs & guides. Tout et plus encore sur LoL par notre team de pasionnés.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fradou.github.io" # the base hostname & protocol for your site

#social info

twitter_username: LoL_of_News
facebook_username: LoLOfNews
github_username:

# collections
collections: 
    music:
        output: true
    teams:
        output: true
    redac:
        output: true


# Build settings
markdown: kramdown
